/* Поправки громкости пьес в дБ — сгенерировано scripts/loudness.mjs (npm run loudness -- --write).
   Не править руками: перезапустить скрипт после изменения аранжировки. Цель -31 дБ полной шкалы. */
export const TRACK_GAIN_DB = {
  dawn: 2,
  ledger: -1.5,
  northlight: 2,
  promenade: 2.5,
  meadow: 3,
  ascent: 0,
  boulevard: -0.5,
  overdrive: -1,
  longwinter: -3,
  emptyhalls: 1.5,
  patience: 1.5,
  deadlock: 0,
  friction: 1,
  collapse: 0,
  panic: 0,
  bankrun: 1,
  warmarch: 0,
  trenches: -2,
  ironmarch: -2,
  curfew: -5,
  glass: 1.5,
  stillness: 0,
  openingbell: 0,
  bidask: 0,
  bearmarket: 1,
  thinvolume: 1,
  marginwire: 0,
  cabinet: 1,
  sixstring: 1.5,
  fullhouse: -0.5,
  nightshift: -1.5,
  treadmill: 1,
  firstlesson: 2.5,
  chalkboard: 1,
  graduation: 0,
  chips: -1.5,
  croupier: -0.5,
  anthem: -1.5,
  rally: 0,
  doorbell: 2,
  decree: -1.5,
  corridors: 1,
  anchor: 3.5,
  firmhand: 1.5,
  hoarfrost: 3,
  homefront: 0,
  parade: -3,
  jackpot: -1,
  residence: 3,
};
export const STINGER_GAIN_DB = {
  victory: 2.5,
  hollow: -1,
  defeat: -3,
  coup: -5.5,
  regime_fall: -3.5,
  restoration: 4,
  prices_stopped: 3.5,
};
